version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shopdevgo
      MYSQL_USER: dev
      MYSQL_PASSWORD: root1234
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6319:6379"
    volumes:
      - redis_data:/data
  crm.shopdev.com:
    container_name: shopdev_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data:
