version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shopdevgo
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6319:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
