server:
  port: 8082

mysql:
  host: 127.0.0.1
  port: 3316
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.log"
  max_size: 500, # megabytes
  max_backups: 3
  max_age: 28   # days
  compress: true # disabled by default
