server:
  port: 8082
database:
  - user: admin
    password: admin
    host: localhost
    dbName: shopdev
  - user: dev
    password: dev
    host: localhost
    dbName: shopdev
security:
  jwt:
    key: b9571055-4b3e-46dd-aeef-18cf62fe6d15